//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace гончарная_мастерская.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_group_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course_group_table()
        {
            this.registration_table = new HashSet<registration_table>();
        }
    
        public int id_course_group { get; set; }
        public int id_name_group { get; set; }
        public int counte_person { get; set; }
        public Nullable<System.DateTime> first_date { get; set; }
        public Nullable<System.DateTime> last_date { get; set; }
        public int curator_id { get; set; }
    
        public virtual info_course_table info_course_table { get; set; }
        public virtual workers_table workers_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registration_table> registration_table { get; set; }
    }
}
