//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace гончарная_мастерская.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class material_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public material_table()
        {
            this.product_table = new HashSet<product_table>();
        }
    
        public int id_material { get; set; }
        public string name_material { get; set; }
        public Nullable<int> color_id { get; set; }
        public Nullable<int> proizvoditel_id { get; set; }
        public int count_package { get; set; }
        public double weight_kg { get; set; }
        public Nullable<System.DateTime> srok_godnosti { get; set; }
        public int barcode { get; set; }
        public Nullable<int> ogneypornost_id { get; set; }
        public int material_category_id { get; set; }
        public int postavshik_id { get; set; }
    
        public virtual color_table color_table { get; set; }
        public virtual material_category_table material_category_table { get; set; }
        public virtual ogneypornost_table ogneypornost_table { get; set; }
        public virtual postavshiki_table postavshiki_table { get; set; }
        public virtual proizvoditeli_table proizvoditeli_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_table> product_table { get; set; }
    }
}
