//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace гончарная_мастерская.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class potteryEntities : DbContext
    {
        public potteryEntities()
            : base("name=potteryEntities")
        {
        }
        private static potteryEntities _context;
        public static potteryEntities GetContext()
        {
            if (_context == null)
            {
                _context = new potteryEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<color_table> color_table { get; set; }
        public virtual DbSet<course_group_table> course_group_table { get; set; }
        public virtual DbSet<dolzhnost_table> dolzhnost_table { get; set; }
        public virtual DbSet<info_course_table> info_course_table { get; set; }
        public virtual DbSet<kategory_product_table> kategory_product_table { get; set; }
        public virtual DbSet<klient_table> klient_table { get; set; }
        public virtual DbSet<material_category_table> material_category_table { get; set; }
        public virtual DbSet<material_table> material_table { get; set; }
        public virtual DbSet<ogneypornost_table> ogneypornost_table { get; set; }
        public virtual DbSet<postavshiki_table> postavshiki_table { get; set; }
        public virtual DbSet<product_table> product_table { get; set; }
        public virtual DbSet<proizvoditeli_table> proizvoditeli_table { get; set; }
        public virtual DbSet<registration_table> registration_table { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<workers_table> workers_table { get; set; }
    }
}
