//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace гончарная_мастерская.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class postavshiki_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public postavshiki_table()
        {
            this.material_table = new HashSet<material_table>();
        }
    
        public int id_postavshika { get; set; }
        public string name_postavshik { get; set; }
        public string index_postavshik { get; set; }
        public string surname_director { get; set; }
        public string name_director { get; set; }
        public string phone_number_postavshik { get; set; }
        public string e_mail_postavshik { get; set; }
        public string inn { get; set; }
        public string kpp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<material_table> material_table { get; set; }
    }
}
