//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace гончарная_мастерская.models
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class product_table
    {
        public string GetPhoto
        {
            get
            {
                if (photo is null)
                    return Directory.GetCurrentDirectory() + @"\Images\picture.png";
                return Directory.GetCurrentDirectory() + @"\Images\" + photo.Trim();
            }
        }
        public int id_product { get; set; }
        public int articul { get; set; }
        public string name_product { get; set; }
        public int category_product { get; set; }
        public int price { get; set; }
        public Nullable<int> material_id { get; set; }
        public int color_id { get; set; }
        public int master_id { get; set; }
        public Nullable<double> lenght { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> height { get; set; }
        public string photo { get; set; }
    
        public virtual color_table color_table { get; set; }
        public virtual kategory_product_table kategory_product_table { get; set; }
        public virtual material_table material_table { get; set; }
        public virtual workers_table workers_table { get; set; }
    }
}
