//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace гончарная_мастерская.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workers_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public workers_table()
        {
            this.course_group_table = new HashSet<course_group_table>();
            this.product_table = new HashSet<product_table>();
        }
    
        public int id_workers { get; set; }
        public string surname_workers { get; set; }
        public string name_workers { get; set; }
        public string otchestvo_workers { get; set; }
        public int dolznost_id { get; set; }
        public string phone_number_workers { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string house { get; set; }
        public string kvartira { get; set; }
        public System.DateTime date_rozhdeniya { get; set; }
        public System.DateTime date_priema_na_raboty { get; set; }
        public int oklad_no_nds { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_group_table> course_group_table { get; set; }
        public virtual dolzhnost_table dolzhnost_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_table> product_table { get; set; }
    }
}
